### ISSUE TITLE
Plugin too verbose

### ISSUE THREAD

**Issue by ictcorebiz** [ansoni/fluent-plugin-json-schema-filter#1]
Hi,

When using the plugin, it returns a "true" and a newline for every checked item. This is filling up my logs wth more than 2 million lines per hour...

When looking at the code, I saw you are using standard **puts** statements, rather than using the logging framework, and making this e.g. log.debug(valid).

```
   def filter_stream(tag, es)
      new_es = MultiEventStream.new
      es.each { |time, record|
        new_record = record.dup
        begin
          valid, error_msg = validate(record)
          puts valid
          puts error_msg

```

Can you please fix this?

**Comment by ictcorebiz** [comment]
@ansoni can you confirm whether you read the issues in this list, since I don't see much action in any of your projects since July, I would like to know whether you still maintain them actively.

**Comment by ansoni** [comment]
This fix was merged and a new gem released awhile back.
